features:
  packages: false
  powershell: false
  environment: false
  symlinks: true
  themes: true
  addons: false
  misc: false

  #pm overrides
  winget: true
  scoop: true
  chocolatey: false

# Environment variables
environment:
  - command: eza
    key: EZA_CONFIG_DIR
    value: .config\eza
  - command: komorebic
    key: KOMOREBI_CONFIG_HOME
    value: .config\komorebi
  - command: jj
    key: JJ_CONFIG
    value: .config\jj
  - command: mise
    key: CARGO_HOME
    value: AppData\Local\Rust\Cargo
  - command: mise
    key: RUSTUP_HOME
    value: AppData\Local\Rust\Rustup
  - command: yazi
    key: YAZI_FILE_ONE
    value: "C:\\Program Files\\Git\\usr\\bin\\file.exe"
  - command: yazi
    key: YAZI_CONFIG_HOME
    value: .config\yazi
  - command: vagrant
    key: VAGRANT_DEFAULT_PROVIDER
    value: virtualbox

# Symlinks
symlinks:
  # Directories to create symlinks for
  # Each directory contains files that will be symlinked to the destination
  directories:
    - source: config/home
      destination: '%USERPROFILE%'
    - source: config/config
      destination: '%USERPROFILE%/.config'
    - source: config/AppData
      destination: '%USERPROFILE%/AppData'

  # Overrides specify paths that should be forced to symlink even if the target exists
  # This is useful for files that may already exist but you want to replace with your config
  # Options:
  # - Exact path: "d:/dots/config/file.txt" (will match only this exact file)
  # - Directory path: "d:/dots/config/dir" (will match all files in this directory)
  # - Wildcard path: "d:/dots/config/*.json" (will match all json files in this directory)
  # - Recursive wildcard: "d:/dots/config/**/*.json" (will match all json files in all subdirectories)
  overrides:
    # Forces Windows Terminal settings to be replaced even if the file already exists
    - config/appdata/local/packages/microsoft.windowsterminal_8wekyb3d8bbwe/localstate/settings.json

addons:
  - command: gh
    command_check: gh extension list
    command_invoke: gh extension install
    install: false
    packages:
      - dlvhdr/gh-dash
      - yuler/gh-download
      - seachicken/gh-poi
      - Link-/gh-token
      - yusukebe/gh-markdown-preview
      - Shresht7/gh-license

# Miscellaneous configurations
misc:
  wsl_install: true

  komorebi:
    # enable: true
    # enable_autostart: true

  yasb:
    # enable: true
    # enable_autostart: true

packages:
  winget:
    additional_args:
      - --exact
      - --silent
      - --accept-package-agreements
      - --accept-source-agreements
    packages:
      # Pre-req
      - id: Git.Git
      - id: Microsoft.PowerShell
      - id: Microsoft.WindowsTerminal
      # - id: Microsoft.WindowsTerminal.Preview

      # Run
      - id: Microsoft.DotNet.SDK.8
      - id: Microsoft.DotNet.SDK.9
      - id: Microsoft.DotNet.Runtime.3_1
      - id: Python.Python.3.13
      - id: AdoptOpenJDK.OpenJDK.11

      # Auth
      - id: Tailscale.Tailscale
      - id: Bitwarden.Bitwarden
      - id: Proton.ProtonVPN

      # Editors
      - id: Microsoft.VisualStudioCode
      - id: ONLYOFFICE.DesktopEditors
      - id: Microsoft.VisualStudio.2022.Community

      # Browsers
      - id: Zen-Team.Zen-Browser
      - id: eloston.ungoogled-chromium

      # Tools
      - id: AngusJohnson.ResourceHacker
      - id: AutoHotkey.AutoHotkey
      - id: AntibodySoftware.WizTree
      - id: DuongDieuPhap.ImageGlass
      - id: Flow-Launcher.Flow-Launcher
      - id: Microsoft.PowerToys
      - id: ShareX.ShareX

      # Comms
      - id: BlueBubbles.BlueBubbles
      - id: Discord.Discord
      - id: SlackTechnologies.Slack
      - id: Valve.Steam

      # Virts
      - id: Hashicorp.Vagrant
      - id: Oracle.VirtualBox

      # Tweaks
      - id: AmN.yasb
      - id: File-New-Project.EarTrumpet
      - id: RamenSoftware.Windhawk
      - id: StartIsBack.StartAllBack

      # Added by sync script
      - id: LesFerch.WinSetView
      - id: Logitech.GHUB
      - id: Logitech.OptionsPlus
      - id: Spotify.Spotify
      - id: RARLab.WinRAR

  scoop:
    additional_args: []
    buckets:
      - name: extras
      - name: versions
      - name: sysinternals
      - name: nerd-fonts
      - name: games
    packages:
      # Pre-req
      - name: aria2
      - name: cacert
      - name: innounp
      - name: wixtoolset
      - name: vcredist2022

      # Extras
      - name: scoop-completion
      - name: scoop-search

      # Git
      - name: bfg
      - name: delta
      - name: diffutils
      - name: gh
      - name: git-aliases
      - name: git-crypt
      - name: git-lfs
      - name: git-sizer
      - name: gitleaks
      - name: lazygit

      # Dev
      - name: bruno
      - name: docker
      - name: ghostscript
      - name: lua
      - name: nodejs
      - name: luarocks
      - name: make
      - name: mariadb
      - name: task
      - name: opentofu
      - name: tree-sitter
      - name: just
      - name: jj

      # Cli
      - name: age
      - name: bat
      - name: btop
      - name: biome
      - name: charm-gum
      - name: chafa
      - name: curl
      - name: dbeaver
      - name: dust
      - name: eza
      - name: fastfetch
      - name: fd
      - name: ffmpeg
      - name: fzf
      - name: glow
      - name: gow
      - name: gpg
      - name: gzip
      - name: gsudo
      - name: imagemagick
      - name: jq
      - name: lazydocker
      - name: mpv
      - name: navi
      - name: neovim
      - name: onefetch
      - name: poppler
      - name: ripgrep
      - name: shfmt
      - name: speedtest-cli
      - name: spicetify-cli
      - name: starship
      - name: termusic
      - name: tldr
      - name: unar
      - name: unzip
      - name: wget
      - name: win32yank
      - name: xh
      - name: yazi
      - name: yq
      - name: yt-dlp
      - name: zoxide

      # Sysinternals
      - name: process-explorer
        scope: global
      - name: procmon
        scope: global
      - name: pskill
        scope: global
      - name: pslist
        scope: global
      - name: psservice
        scope: global
      - name: autoruns
        scope: global
      - name: autologon
        scope: global

      # Tools
      - name: 7zip
      - name: bitwarden-cli
      - name: fancontrol
      - name: komorebi
      - name: krita
      - name: obsidian
      - name: openrgb
      - name: sops
      - name: iperf3
      - name: keyboard-chatter-blocker
      - name: librehardwaremonitor
      - name: unigetui
      - name: whkd
      - name: zoom

      # Tweaks
      - name: micaforeveryone
      - name: nilesoft-shell
      - name: secureuxtheme
      - name: winaero-tweaker

      # Fonts
      - name: Maple-Mono

      # Added by sync script
      - name: via
      - name: depends
      - name: everything
      - name: nirlauncher
      - name: pathofbuilding-community
      - name: wezterm
      - name: altsnap
      - name: bulk-crap-uninstaller
      - name: msys2
      - name: oh-my-posh
      - name: qbittorrent
      - name: sqlite
      - name: topgrade
      - name: audacity
      - name: systeminformer-nightly
      - name: upx

  chocolatey:
    additional_args:
      - -y
      - --no-progress
    packages:
      - name: choco-cleaner

powershell:
  experimental_features:
    enable: true
    features:
      - PSNativeWindowsTildeExpansion
      - PSFeedbackProvider
  modules:
    - name: BurntToast
    - name: CompletionPredictor
    - name: PSScriptAnalyzer
    - name: DockerCompletion
    - name: DotNetVersionLister
    - name: PSFzf
    - name: posh-git
    - name: PSWindowsUpdate
    - name: Microsoft.PowerShell.SecretManagement
    - name: Microsoft.PowerShell.SecretStore
    - name: Microsoft.WinGet.CommandNotFound
    - name: Terminal-Icons
    - name: ps-color-scripts
    - name: powershell-yaml
    - name: PSScriptTools
    - name: PSParseHTML
    - name: PSToml
  additional_args:
    - -Scope
    - CurrentUser
    - -Force
    - -AllowClobber
