watch_stylesheet: true
watch_config: true
debug: false

# This komorebi setting will be used for tray context menu.
# If you don't use komorebi, you can remove this section.
komorebi:
  start_command: 'komorebic start --whkd'
  stop_command: 'komorebic stop --whkd'
  reload_command: 'komorebic stop --whkd && komorebic start --whkd'

bars:
  status-bar:
    enabled: true
    screens: ['*']
    class_name: 'yasb-bar'
    alignment:
      position: 'top'
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: '100%'
      height: 35
    padding:
      top: 5
      left: 15
      bottom: 5
      right: 15
    widgets:
      left: ['komorebi_workspaces', 'komorebi_active_layout', 'apps', 'active_window']
      center: ['clock']
      right: [
          'media',
          'notifications',
          # 'update_check',
          'wifi',
          'github',
          'cpu',
          'memory',
          'weather',
          'microphone',
          'volume',
          'power_menu',
        ]

widgets:
  win_button:
    type: 'yasb.custom.CustomWidget'
    options:
      label: "\ue62a"
      label_alt: "\ue62a"
      class_name: 'system-widget'
      callbacks:
        on_left: 'exec start_menu'

  komorebi_workspaces:
    type: 'komorebi.workspaces.WorkspaceWidget'
    options:
      label_offline: 'Komorebi Offline'
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "\udb81\udc3e"
      label_default_name: '{index}'
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true

  komorebi_active_layout:
    type: 'komorebi.active_layout.ActiveLayoutWidget'
    options:
      hide_if_offline: true
      label: '{icon}'
      layouts: [
          'ultrawide_vertical_stack',
          'bsp',
          'columns',
          'grid',
          'rows',
          # 'vertical_stack',
          # 'horizontal_stack',
          # 'right_main_vertical_stack',
        ]
      layout_icons:
        bsp: 'BSP'
        columns: 'COLS'
        rows: 'ROWS'
        grid: 'GRID'
        vertical_stack: 'V-STACK'
        horizontal_stack: 'H-STACK'
        ultrawide_vertical_stack: 'STACK'
        right_main_vertical_stack: 'RMV-STACK'
        monocle: 'MONOCLE'
        maximised: 'MAX'
        floating: 'FLOAT'
        paused: 'PAUSED'
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_tiling'
        on_right: 'first_layout'

  active_window:
    type: 'yasb.active_window.ActiveWindowWidget'
    options:
      label: '{win[title]}'
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ''
      label_icon: true
      label_icon_size: 16
      #TODO: add callbacks
      max_length: 56
      max_length_ellipsis: '...'
      monitor_exclusive: true

  clock:
    type: 'yasb.clock.ClockWidget'
    options:
      label: '{%a %d, %b %I:%M %p}'
      label_alt: '{%A %d %B %Y, %H:%M}'
      #locale: 'en_EN' # Langugae for date, you can set your own, example fr_FR
      timezones: [] #Looking up time zone info from registry
      #timezones: ["America/Montreal"]

  notifications:
    type: 'yasb.notifications.NotificationsWidget'
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: '{count} notifications'
      hide_empty: false
      tooltip: false
      callbacks:
        on_left: 'toggle_notification'
        on_right: 'do_nothing'
        on_middle: 'toggle_label'
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8

  microphone:
    type: 'yasb.microphone.MicrophoneWidget'
    options:
      label: '<span>{icon}</span>'
      label_alt: '<span>{icon}</span> {level}%'
      icons:
        normal: "\uf130"
        muted: "\uf131"
      callbacks:
        on_left: 'toggle_mute'
        on_middle: 'toggle_label'
        on_right: 'exec cmd.exe /c start ms-settings:sound'
  apps:
    type: 'yasb.applications.ApplicationsWidget'
    options:
      label: '{data}'
      app_list:
        - { icon: "\udb82\ude1e", launch: 'code' }
        - { icon: "\uf489", launch: 'wt' }
        # - { icon: "\uf1ff", launch: "C:\\Users\\cwel\\AppData\\Local\\Discord\\Update.exe" }
        # - { icon: "\uf0a2", launch: 'notification_center' }
        - { icon: "\ueb51", launch: 'cmd.exe /c start ms-settings:' }
        - { icon: "\uf46a", launch: 'cmd.exe /c start ms-settings:windowsupdate' }
        - { icon: "\uf422", launch: 'launcher' }
        - { icon: "\uf413", launch: 'explorer' }
        # Currently available to use quick_settings, notification_center, search, widget, launcher (launcher will trigger ALT+A)

  media:
    type: 'yasb.media.MediaWidget'
    options:
      label: "<span>\uf001</span> {title}"
      label_alt: "<span>\uf001</span> {title} - {artist}"
      max_field_size:
        label: 20
        label_alt: 30
      callbacks:
        on_left: 'toggle_label'
        on_middle: 'do_nothing' #TODO: write script to launch/focus application where active media is playing
        on_right: 'do_nothing' #TODO: launch sound panel ?
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 15 # Set to 0 for square corners
      icons:
        prev_track: "\ue892"
        next_track: "\ue893"
        play: "\ue768"
        pause: "\ue769"

  github:
    type: 'yasb.github.GithubWidget'
    options:
      label: "<span>\ueba1</span>"
      label_alt: 'Notifications {data}' # {data} return number of unread notification
      token: env # YASB_GITHUB_TOKEN - GitHub Personal access tokens (classic) https://github.com/settings/tokens
      max_notification: 20 # Max number of notification displaying in menu max: 50
      only_unread: false # Show only unread or all notifications;
      max_field_size: 54 # Max characters in title before truncation.
      update_interval: 300 # Check for new notification in seconds
      menu:
        blur: true
        round_corners: true
        round_corners_type: 'normal'
        alignment: 'right'
        direction: 'down'
        distance: 5

  wallpapers:
    type: 'yasb.wallpapers.WallpapersWidget'
    options:
      label: "<span>\udb83\ude09</span>"
    image_path: "C:\\users\\cwel\\Pictures\\walls" # Example path to folder with images
    change_automatically: false # Automatically change wallpaper
    update_interval: 60 # If change_automatically is true, update interval in seconds
    gallery:
      enabled: true
      blur: true
      image_width: 220
      image_per_page: 8
      show_buttons: false
      orientation: 'portrait'
      image_spacing: 8
      lazy_load: true
      lazy_load_delay: 80
      lazy_load_fadein: 400
      image_corner_radius: 20
      enable_cache: true
    run_after: # List of functions to run after wallpaper is updated
      - 'wal -s -t -e -q -n -i {image}' # Example command to run after wallpaper is updated
      - 'cmd.exe /c start /min pwsh ./yasb.ps1' # Example command to run after wallpaper is updated
  home:
    type: 'yasb.home.HomeWidget'
    options:
      label: "<span>\udb81\udf17</span>"
      menu_list:
        - { title: 'User Home', path: '~' }
        - { title: 'Downloads', path: "~\\Downloads" }
        - { title: 'Documents', path: "~\\Documents" }
        - { title: 'Pictures', path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: false

  cpu:
    type: 'yasb.cpu.CpuWidget'
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: 'exec cmd /c Taskmgr'

  memory:
    type: 'yasb.memory.MemoryWidget'
    options:
      label: "<span>\uefc5</span> {virtual_mem_free}"
      label_alt: "<span>\uefc5</span> {virtual_mem_percent}%"
      update_interval: 10000
      callbacks:
        on_right: 'exec cmd /c Taskmgr'

  weather:
    type: 'yasb.weather.WeatherWidget'
    options:
      label: '<span>{icon}</span> {temp}'
      label_alt: '{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}'
      api_key: env # Will use YASB_WEATHER_API_KEY environment variable
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      units: 'imperial'
      location: '22213' # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: 'toggle_label'
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzard: "\uebaa"
        default: "\uebaa"
        # https://www.weatherapi.com/docs/
        # Usage {temp}, {min_temp}, {max_temp}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}

  volume:
    type: 'yasb.volume.VolumeWidget'
    options:
      label: '<span>{icon}</span> {level}'
      label_alt: '{volume}'
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      callbacks:
        on_right: 'exec cmd.exe /c start ms-settings:sound'

  power_menu:
    type: 'yasb.power_menu.PowerMenuWidget'
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 300 # Milisecond
      button_row: 3 # Number of buttons in row, min 1 max 5
      buttons:
        lock: ["\uea75", 'Lock']
        signout: ["\udb80\udf43", 'Sign out']
        #sleep: ["\u23fe","Sleep"]
        shutdown: ["\uf011", 'Shut Down']
        restart: ["\uead2", 'Restart']
        hibernate: ["\uf28e", 'Hibernate']
        cancel: ["\udb81\udf3a", 'Cancel']
        #force_shutdown: ["\uf011","Force Shut Down"]
        #force_restart: ["\uead2","Force Restart"]

  wifi:
    type: 'yasb.wifi.WifiWidget'
    options:
      label: '<span>{wifi_icon}</span>'
      label_alt: '{wifi_name}'
      update_interval: 5000
      callbacks:
        on_left: 'exec cmd.exe /c start ms-settings:network'
        on_middle: 'do_nothing'
        on_right: 'toggle_label'
      wifi_icons: [
          "\udb82\udd2e", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-20% strength
          "\udb82\udd22", # Icon for 21-40% strength
          "\udb82\udd25", # Icon for 41-80% strength
          "\udb82\udd28", # Icon for 81-100% strength
        ]

  update:
    type: 'yasb.update_check.UpdateCheckWidget'
    options:
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span> {count}"
        interval: 180
        exclude: [Discord]
      windows_update:
        enabled: false
        label: "<span>\uf0ab</span> {count}"
        tooltip: true
        interval: 240
        exclude: []

  language:
    type: 'yasb.language.LanguageWidget'
    options:
      label: "<span>\uf11c</span>{lang[language_code]}"
      label_alt: '{lang[full_name]}'
      update_interval: 5
      callbacks:
        on_left: 'toggle_label'
        on_middle: 'do_nothing'
        on_right: 'do_nothing'
