# yaml-language-server: $schema=https://dlvhdr.github.io/gh-dash/configuration/gh-dash/schema.json
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparators: true
      compact: false
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#cba6f7"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f9e2af"
      success: "#a6e3a1"
      error: "#f38ba8"
    background:
      selected: "#313244"
    border:
      primary: "#cba6f7"
      secondary: "#45475a"
      faint: "#313244"

prSections:
  - title: Pull Requests
    filters: is:open author:@me
    layout:
      author:
        hidden: true
  - title: Review
    filters: is:open review-requested:@me
  - title: Commented
    filters: commenter:@me

issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Commented
    filters: is:open commenter:@me
  - title: Assigned
    filters: is:open assignee:@me

defaults:
  layout:
    prs:
      repo:
        grow: true
        width: 10
        hidden: false
  prsLimit: 20
  issuesLimit: 20
  preview:
    open: true
    width: 60
  refetchIntervalMinutes: 30

repoPaths:
  :owner/:repo: /g/repos/:owner/:repo
  cwelsys/*: /g/projects/*
  cwelsys/windots: /g/dotfiles

pager:
  diff: delta

keybindings:
  universal:
    - key: g
      command: >
        cd {{.RepoPath}} && lazygit

  prs:
    - key: a
      command: >
        cd {{.RepoPath}} && git add -A && lazygit
    - key: v
      command: >
        gh pr review --repo {{.RepoName}} --approve --body "$(gum input --prompt='Approval Comment: ')" {{.PrNumber}}

  issues:
    - key: P
      command: gh issue pin {{.IssueNumber}} --repo {{.RepoName}}

confirmQuit: false