#yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# NOTE:
# dP                                            oo   dP
# 88                                                 88
# 88        .d8888b. d888888b dP    dP .d8888b. dP d8888P
# 88        88'  `88    .d8P' 88    88 88'  `88 88   88
# 88        88.  .88  .Y8P    88.  .88 88.  .88 88   88
# 88888888P `88888P8 d888888P `8888P88 `8888P88 dP   dP
#                                  .88      .88
#                              d8888P   d8888P
gui:
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    '*': '#b4befe'
  mouseEvents: true
  nerdFontsVersion: '3'
  mainPanelSplitMode: flexible
  commitLength:
    show: true
  splitDiff: auto
  spinner:
    frames:
      - '⣷ '
      - '⣯ '
      - '⣟ '
      - '⡿ '
      - '⢿ '
      - '⣻ '
      - '⣽ '
      - '⣾ '
    rate: 100
  statusPanelView: allBranchesLog
  commandLogSize: 2
  showRandomTip: false

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false
  autoFetch: true
  autoRefresh: true
  branchLogCmd: git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --
  allBranchesLogCmd: git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: false
  log:
    order: topo-order
    showGraph: always
    showWholeGraph: false

update:
  method: prompt
  days: 14

refresher:
  refreshInterval: 10
  fetchInterval: 60

confirmOnQuit: false

os:
  editPreset: 'code'

customCommands:
  - key: 'b'
    command: 'gh browse'
    context: 'files'
  - key: 'b'
    command: 'gh browse "{{.SelectedLocalCommit.Sha}}"'
    context: 'commits'
  - key: 'o'
    command: 'gh pr view --web'
    description: 'View PR on GitHub'
    context: 'global'
  - key: 'o'
    command: 'gh pr view --web {{.SelectedLocalBranch.Name}}'
    description: 'View PR on GitHub'
    context: 'localBranches'
    loadingText: 'Opening GitHub...'
    subprocess: false
  - key: 'F'
    command: 'git push --force-with-lease --no-verify'
    context: 'localBranches'

notARepository: skip

promptToReturnFromSubprocess: true
